# Generated by Django 5.2.17 on 2026-08-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('institution_en', models.CharField(max_length=200, null=True)),
                ('institution_pt_br', models.CharField(max_length=200, null=True)),
                ('degree', models.CharField(max_length=200)),
                ('degree_en', models.CharField(max_length=200, null=True)),
                ('degree_pt_br', models.CharField(max_length=200, null=True)),
                ('field_of_study', models.CharField(max_length=200)),
                ('field_of_study_en', models.CharField(max_length=200, null=True)),
                ('field_of_study_pt_br', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_pt_br', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_pt_br', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('redact_company_name', models.BooleanField(default=False, help_text='If checked, the public site shows company_description instead of company_name.')),
                ('company_description', models.TextField(blank=True, help_text='Fallback text shown publicly in place of the company name when redacted.')),
                ('company_description_en', models.TextField(blank=True, help_text='Fallback text shown publicly in place of the company name when redacted.', null=True)),
                ('company_description_pt_br', models.TextField(blank=True, help_text='Fallback text shown publicly in place of the company name when redacted.', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for a current role.', null=True)),
                ('description', models.TextField(blank=True, help_text='Free text: bullet points, achievements, figures, skills used.')),
                ('description_en', models.TextField(blank=True, help_text='Free text: bullet points, achievements, figures, skills used.', null=True)),
                ('description_pt_br', models.TextField(blank=True, help_text='Free text: bullet points, achievements, figures, skills used.', null=True)),
                ('background_image', models.ImageField(upload_to='timeline/experience/')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('link', 'Link'), ('document', 'Document')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_pt_br', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/evidence/')),
                ('link', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='timeline/evidence/documents/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='timeline.experience')),
            ],
        ),
    ]
