# Generated by Django 5.2.17 on 2026-08-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_pt_br', models.TextField(null=True)),
            ],
        ),
    ]
