# Generated by Django 5.2.17 on 2026-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.URLField(blank=True, help_text="Company website. Only shown/linked when the name isn't redacted."),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_description',
            field=models.TextField(blank=True, help_text='Short description of the company. Shown below the company name; also used as the public fallback text in place of the name when redacted.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_description_en',
            field=models.TextField(blank=True, help_text='Short description of the company. Shown below the company name; also used as the public fallback text in place of the name when redacted.', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_description_pt_br',
            field=models.TextField(blank=True, help_text='Short description of the company. Shown below the company name; also used as the public fallback text in place of the name when redacted.', null=True),
        ),
    ]
