# Generated by Django 5.2.17 on 2026-08-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_experience_company_website_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_pt_br', models.CharField(max_length=100, null=True)),
                ('proficiency', models.CharField(choices=[('a1', 'Beginner (A1)'), ('a2', 'Elementary (A2)'), ('b1', 'Intermediate (B1)'), ('b2', 'Upper Intermediate (B2)'), ('c1', 'Advanced (C1)'), ('c2', 'Proficient (C2)'), ('native', 'Native')], max_length=10)),
            ],
            options={
                'ordering': ['-proficiency'],
            },
        ),
    ]
