# Generated by Django 5.2.17 on 2026-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_pt_br', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_pt_br', models.TextField(null=True)),
                ('screenshot', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField()),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to keep a placeholder/WIP entry hidden from the live site.')),
            ],
        ),
    ]
